# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Laura Moreno Martínez"
email: laura.morenomartinez@unipd.it
description: >- # this means to ignore newlines until "baseurl:"
twitter_username: username
github_username: lauramoremar
minimal_mistakes_skin: dirt #contrast #default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  #- jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-paginate  
github: [metadata]
 
author:
  name   : "Laura Moreno Martínez"
  avatar : "/assets/images/laura2020.jpeg"
  bio    : "Postdoctoral reasearcher at Institut für Statik und Dynamik (TUBS)"
  #"Postdoctoral researcher at University of Padua, Italy."
  #"Torre Archimede, Office 330, va Trieste 63, 35121 Padova"
  location : "Braunschweig, Germany"
  # "Padova, Italia"
  links:
    - label: "Personal address"
      icon: "fas fa-fw fa-envelope-open"
      url: "mailto: moremar.laura@gmail.com"
    - label: "Email TUBS (Braunschweig)"
      icon: "fas fa-fw fa-envelope-open"
      url: "mailto: laura.moreno-martinez@tu-braunschweig.de"
    #- label: "Email Unipd (Padova)"
    #  icon: "fas fa-fw fa-envelope-open"
      #url: "mailto: laura.morenomartinez@unipd.it"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lauramoremar/"
    #- label: "Twitter"
      #icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/"
    - label: "GitHub: lauramoremar"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lauramoremar"
    #- label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Laura-Moreno-17"
    - label: "ORCID: 0000-0002-8163-0877"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8163-0877"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=5ziDxTEAAAAJ&hl=es"
    - label: "Web of Science"
      icon: "fab fa-fw fa-web-of-science"
      url: "https://www.webofscience.com/wos/author/record/3720598"
    - label: "Scopus ID: 57209293676"
      icon: "fab fa-fw fa-scopus"
      url: "https://www.scopus.com/authid/detail.uri?authorId=57209293676"


sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


footer:
  links:
    #- label: "Twitter"
      #icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lauramoremar"
    #- label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/laura-moreno-mart%C3%ADnez-06534090/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
